---
title: "Tahoe Worker Flow"
output: html_document
---

```{r setup, include=FALSE,messages=F}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(knitr)
library(kableExtra)
```

## CTPP Summary

This section summaries the CTPP worker flow.

```{r,output=F,echo=F,eval=T}
cttSumm <- read_excel('../../ExternalWorker/CTPP/CTPP_summary analysis.xlsx',sheet='Tract',range = 'A30:FN64')
cttSumm <- cttSumm %>% gather('DestinationTract','workerFlow',-OriginTract)

cttSumm2 <- cttSumm %>%  mutate(
    DestinationTract2 = ifelse(DestinationTract %in% OriginTract, DestinationTract, substr(DestinationTract,1,2))    
) %>% filter((DestinationTract2 %in% OriginTract | DestinationTract2 %in% c('06','32'))) %>%
    filter(workerFlow>0)
TractToDistrict <- read_excel('../../ExternalWorker/CTPP/TractToDistrict.xlsx',sheet='Sheet1',range = 'A1:B26') 

cttSumm3 <- cttSumm2 %>% left_join(TractToDistrict,by=c('OriginTract'='Tract')) %>% rename(OrigDistrict=District) %>% 
    left_join(TractToDistrict,by=c('DestinationTract'='Tract')) %>% rename(DestDistrict=District) %>% 
    mutate(OrigDistrict=ifelse(is.na(OrigDistrict),substr(OriginTract,1,6),OrigDistrict),
           DestDistrict=ifelse(is.na(DestDistrict),substr(DestinationTract,1,6),DestDistrict)) %>% 
    mutate(DestDistrict=ifelse(DestDistrict %in% OrigDistrict,DestDistrict,substr(DestDistrict,1,2) ))

cttSumm4 <- cttSumm3 %>% group_by(OrigDistrict,DestDistrict) %>% summarise(workerFlow=sum(workerFlow))
# Keep only flows that have either an internal or external point in the Tahoe region
cttSumm4 <- cttSumm4 %>% filter(OrigDistrict %in% c('11','12','13','14','15','16','17')|DestDistrict %in% c('11','12','13','14','15','16','17'))


cttSumm5 <- cttSumm4 %>% spread(key='DestDistrict',value='workerFlow')
cttSumm5[is.na(cttSumm5)] <- 0

tempRowSum <- cttSumm5 %>% ungroup() %>% summarise_at(2:ncol(cttSumm5),sum) %>% mutate(OrigDistrict='Total')
cttSumm6 <- rbind.data.frame(cttSumm5,tempRowSum)
cttSumm6$Total <- cttSumm6 %>% ungroup() %>% dplyr::select(2:ncol(cttSumm6)) %>% t() %>% colSums()

cttSumm6 <- cttSumm6 %>% ungroup() %>% mutate_at(2:ncol(cttSumm6),round) %>% mutate_at(2:ncol(cttSumm6),format,big.mark=',')
```


```{r,echo=F,eval=T}
kable(cttSumm6,caption='CTPP District-District Worker Flow (from Tract-Tract)',align='r') %>% kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

# Streetlight Data Summary

```{r,output=F,message=F,echo=F,eval=T,results=F,warning=F}

# The conversion to data.frame and then back to tibble is to get rid of spaces in the variable names. data.frame replaces it with a period. Easier to work with spaces.

secondData <- read_csv('../RawData/83140_Second/83140_Second_odg_all.csv') %>% data.frame() %>% as_tibble()
secondData <- secondData %>% filter(Day.Part!='0: All Day (12am-12am)') %>% filter(Day.Type=='1: Weekday (M-Th)') 

secondData_traveler <- read_csv('../RawData/83140_Second/83140_Second_odg_traveler_all.csv') %>% data.frame() %>% as_tibble()
secondData_traveler <- secondData_traveler %>% filter(Day.Part!='0: All Day (12am-12am)') %>% filter(Day.Type=='1: Weekday (M-Th)') 

countyTahoe <- c('06_003','06_017','06_057','06_061','32_005','32_019','32_029','32_031','32_510')

secondData <- secondData %>% 
    left_join(secondData_traveler %>% select(Day.Part,Origin.Zone.Name,Destination.Zone.Name,Purpose.HBW..percent.)) %>% 
    mutate(Purpose.HBW..percent.=as.numeric(Purpose.HBW..percent.)) %>% 
    replace_na(list(Purpose.HBW..percent.=0)) %>% 
    mutate(HBW_Vol = Average.Daily.O.D.Traffic..StL.Volume.*Purpose.HBW..percent.) %>% 
    select(-Type.of.Travel,-Day.Type,
           -Origin.Zone.Is.Pass.Through,-Origin.Zone.Direction..degrees.,-Origin.Zone.is.Bi.Direction,
           -Destination.Zone.Is.Pass.Through,-Destination.Zone.Direction..degrees.,-Destination.Zone.is.Bi.Direction,
           -Avg.Trip.Duration..sec.,-Origin.Zone.ID,-Destination.Zone.ID,-Average.Daily.Origin.Zone.Traffic..StL.Volume.,
           -Average.Daily.Destination.Zone.Traffic..StL.Volume.,-Purpose.HBW..percent.)

# 1. Zones that are not based on census boundary are removed, example the Gates
# 2. Identify the zones State. County and Tract. 

TractToDistrict <- read_excel('../../ExternalWorker/CTPP/TractToDistrict.xlsx',sheet='Sheet1',range = 'A1:B26') 
TractToDistrict2 <- TractToDistrict %>% mutate(STATE=substr(Tract,1,2),COUNTY=substr(Tract,4,6),TRACTCE=substr(Tract,8,13)) %>% select(-Tract,-District)

secondData <- secondData %>% filter(!(Origin.Zone.Name %in% paste0('E',1:13)) & !(Destination.Zone.Name %in% paste0('E',1:13)))

cleanData <- secondData %>% 
    left_join(TractToDistrict2,by=c('Origin.Zone.Name'='TRACTCE'))      %>% rename(OrigSTATE=STATE,OrigCOUNTY=COUNTY) %>% mutate(OrigTRACT=Origin.Zone.Name) %>% 
    left_join(TractToDistrict2,by=c('Destination.Zone.Name'='TRACTCE')) %>% rename(DestSTATE=STATE,DestCOUNTY=COUNTY) %>% mutate(DestTRACT=Destination.Zone.Name) %>% 
    mutate(OrigSTATE=ifelse(Origin.Zone.Source!='Input',substr(Origin.Zone.Name,2,3),OrigSTATE),
           OrigCOUNTY=ifelse(Origin.Zone.Source!='Input',substr(Origin.Zone.Name,4,6),OrigCOUNTY),
           OrigTRACT=ifelse(Origin.Zone.Source!='Input',substr(Origin.Zone.Name,7,12),OrigTRACT),
           DestSTATE=ifelse(Destination.Zone.Source!='Input',substr(Destination.Zone.Name,2,3),DestSTATE),
           DestCOUNTY=ifelse(Destination.Zone.Source!='Input',substr(Destination.Zone.Name,4,6),DestCOUNTY),
           DestTRACT=ifelse(Destination.Zone.Source!='Input',substr(Destination.Zone.Name,7,12),DestTRACT)
           ) %>% 
    mutate(OrigID = paste0(OrigSTATE,'_',OrigCOUNTY,'_',OrigTRACT),
           DestID = paste0(DestSTATE,'_',DestCOUNTY,'_',DestTRACT)) %>% 
    left_join(TractToDistrict,by=c('OrigID'='Tract')) %>% rename(OrigDistrict=District) %>% 
    left_join(TractToDistrict,by=c('DestID'='Tract')) %>% rename(DestDistrict=District) %>% 
    filter(OrigSTATE %in% c('06','32') & DestSTATE %in% c('06','32')) %>% 
    mutate(Orig_ST_CNTY = paste0(OrigSTATE,"_",OrigCOUNTY),
           Dest_ST_CNTY = paste0(DestSTATE,"_",DestCOUNTY)) %>% 
    mutate(OrigDistrict = ifelse(is.na(OrigDistrict),ifelse(Orig_ST_CNTY %in% countyTahoe,Orig_ST_CNTY,OrigSTATE ),OrigDistrict),
           DestDistrict = ifelse(is.na(DestDistrict),ifelse(Dest_ST_CNTY %in% countyTahoe,Dest_ST_CNTY,DestSTATE ),DestDistrict)
           )
cleanData2 <- cleanData %>% 
    filter(Day.Part %in% c('1: Early AM (12am-6am)','2: Peak AM (6am-10am)')) %>% 
    group_by(OrigDistrict,DestDistrict) %>% summarise(NumWTrips=sum(HBW_Vol))

cleanData3 <- cleanData2 %>% spread(key='DestDistrict',value='NumWTrips')
cleanData3[is.na(cleanData3)] <- 0

tempRowSum <- cleanData3 %>% ungroup() %>% summarise_at(2:ncol(cleanData3),sum) %>% mutate(OrigDistrict='Total')
cleanData4 <- rbind.data.frame(cleanData3,tempRowSum)
cleanData4$Total <- cleanData4 %>% ungroup() %>% dplyr::select(2:ncol(cleanData4)) %>% t() %>% colSums()

cleanData4 <- cleanData4 %>% ungroup() %>% mutate_at(2:ncol(cleanData4),round) %>% mutate_at(2:ncol(cleanData4),format,big.mark=',')

```

```{r,echo=F,eval=T}
kable(cleanData4,caption='Streetlight Data District-District Work Trip Flow',align='r') %>% kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```
