---
title: "Frequently Asked Questions"
output: html_document
---

# High Level Questions

* How does the model incorporate VHRs (vacation home rentals)? 

> In the file called "SocioEcon_SUMMER" (or WINTER), there is a field called "total_residential_units", and a field called "census_occ_rate".  The product of these two numbers provides the number of full-time resident _occupied_ housing units.  Additionally, in the file called "OvernightVisitorZonalData_SUMMER" (or winter), there is a field called "percentHouseSeasonal".  For each zone, if you take "total_residential_units" subtract the number of full-time resident occupied units and multiply by "percentHouseSeasonal", you will get the number of housing units owned by seasonal residents.  Any residential units left over in a zone can be considered VHRs. These residential units, not occupied by residents or by seasonal residents are populated in a given scenario with overnight visitors based on the occupancy rate identified in "VisitorOccupancyRates" in the field called "house".     

* Can the model be used to estimate project level VMT? (eg a new event center or a highway realignment)

> In the case of an event center, presumably the employment levels of the region would change (SocioEcon_SEASON, emp_srvc in that zone would increase).  This will affect resident and external worker destination choices for work tours and it will affect destinations for day and/or overnight visitor tours. That said, event centers that host weekend events and/or large concerts that require only temporary staffing during the event will require some creativity in generating trips.  The regional model may not be the best choice in looking at VMT generated by specific events.    
> In the case of a highway realignment, the path choices will differ which will lead to different VMT levels.
> So short answer is yes, model can be used to estimate project level VMT but careful consideration of the exact nature of the project must be made.    

* How does the model account for rideshare (uber/lyft)? 

> The Tahoe AB model as it is currently defined does not account for rideshare; however, modifications could be made to the mode choice model for both residents and visitors to include the rideshare mode.  

* How does the model use traffic counts to inform the VMT estimate?

> Traffic counts are used to validate the assignment step of the model.  Prior to assignment, resident and visitor trip origins and destinations are determined.  It is within the assignment step that the _path_ taken to get from origin to destination is determined.  When a model is validated, the assigned link volumes are compared to traffic counts along the same link.  If there is a mismatch - either too many assigned trips or too few - model components and counts are re-examined.  Possible explanations are too many trips are being made (not enough "stay at home" patterns), trip origin/destinations need to be revised, certain paths are too favorable (speeds are too high or capacities too much), or the counts have inconsistencies that can't be explained.  Traffic counts are an important part of validating a model but are not directly used to derive VMT estimates from the regional model.  

* How does the model estimate the average trip length?

> Activity-based models forecast both "tours" and "trips".  A "tour" is a full circle - you start at home, you go somewhere/s, you return home.  A "trip" is the parts of that circle -  the part from home to somewhere and the other part from somewhere to home.  Activity-based models came about because people tend to think about travel more in terms of a "tour" than a "trip" - we plan our day based on the activities we need to attend (work, coffee shop, dropping off children, stop at store) and we plan for travel with the whole picture in mind. A work "tour" with an intermediate outbound stop means that I'm leaving my house with the purpose of going to work, but I'm stopping along the way to drop off my dry cleaning (hopefully at a place along my route to work) and after work, I'm going straight home. So back to the question - the model can estimate both an average "work" trip length (by looking at the distance I go to/from work) but can also estimate my average trip length by looking at the distance from home to dry-cleaning + dry-cleaning to work + work to home and dividing by 3 (total number of trips in my tour).  For each person/tour party, the model determines the number of trips (the denominator) and the trip origins and destinations (the sum of the distances between all of those) (the numerator).  The distance of all trips divided by the total number of trips gives average trip length.  There are many ways this metric can be segmented - by purpose, by traveler type, by tour purpose, by trip purpose, etc.    

* For overnight visitors, does the model include the trips/distances of their trips going to their overnight destination from their permanent home or just after they reach their overnight destination?

> Overnight visitors are assumed to already be in the region on the model day.  External station volumes are assumed to be made up of residents exiting/entering the region on the model day, plus external workers entering/exiting the region on the model day, day visitors entering/exiting the region on the model day and thru-trips entering/exiting the region on the model day.  For day visitors and thru-trips, trip distances start and end at the external stations.  While reality is that external station traffic also includes overnight visitors exiting/entering the region, this simplifying assumption provided a control on the number of day and thru-trips. Trips made by overnight visitors on the model day are included in their VMT.  

* How does the model estimate the total number of day visitors and overnight visitors?

> The model starts with Overnight Visitors.  The OvernightVisitorZonalData_SEASON file and the VisitorOccupancyRates file determine the availability of overnight accomodations (by type - hotelmotel, resort, casino, campground, VHRs) in each zone.  Example: Zone 20 has 100 hotel rooms and the occupancy rate is 50% - this means 50 hotel rooms in Zone 20 are occupied.  50 overnight visitor travel parties (more on how many people constitute a party below) will be synthesized and that zone will be their "home" location (their origin zone).  The composition of those travel parties will be determined based on a series of random draws of the travel parties that were surveyed during the Visitor Survey. For example, there were 231 overnight visitor travel parties surveyed that stayed in a hotel/motel.  Imagine that these parties are put in a hat - for each hotel room that is occupied, the model reaches into the hat and pulls out a travel party and assigns them to that room (really assigns their origin to that zone).  The model then puts that party back in the hat, and reaches in again and pulls another one out (could be the same one).  This happens over and over until all hotel/motel rooms in Zone 20 are filled.  Same is done for Casino rooms available, same for resort rooms, same for houses, same for campgrounds - for each zone in the region that has these accomodation types.  Each stay type has a hat filled with travel parties that stayed in that particular accomodation.  See "VisitorModels", "Population Synthesis" page on the Tahoe Documentation for sample sizes of each accomodation type.  The number of day visitors was backed into during model development by using an average occupancy rate, the external station counts, and the results of the resident and external worker models.  Assume an external station has a daily count of 100 trips.  Residents and external workers accounted for 40 of them (as determined by running these models).  The Tahoe ABM assumes that day and thru-visitors account for the remaining 60.  A license plate survey that was done at the same time as resident and visitor model surveys was used to determine how many of the remaining 60 trips were thru-trips, leaving the rest to be modeled as day-visitors. During base year calibration, the number of overnight visitors (based on an average occupancy rate at each accomodation type by season) was divided by the number of day visitors at each external station and that factor is stored in the file called "DayVisitorZonalData" in the field called "overnight2day".  During a forecast run, if the overnight occupancy rates change and the number of overnight visitors goes up or down, the number of day visitors entering/exiting at a particular external station will also change as the number of day visitors is the number of overnight visitors multiplied by the overnight2day factor. Once the model determines how many day visitor travel parties are at each external station on the model day, it pulls day visitor travel parties from a hat full of the observed day vistor travel parties.  The model uses an identical procedure to synthesize the thru-visitor population.  With both the day visitor and the thru visitor population being tied to the overnight visitor population, the scenario-specific occupancy rates (VisitorOccupancyRate.csv) and the OvernightVisitorZonalData_SEASON are the two inputs that essentially determine the visitor population in the region for a given scenario.     
> 

# Technical Questions

* How is the 'vmt_summary' file computed? (ie Why is the total VMT in the 'vmt_summary' file much greater than the total VMT found on the roadway network?)

> Answer to this question
    
* What data sources were used to develop our network file? (eg speeds, lanes, etc)

> The network was developed by TRPA staff - I believe it was originally developed in Tranplan and imported into TransCAD.  It is likely due for some revisions and a careful review.  
    
* Does the 'shared auto' mode include rideshare (uber/lyft)?

> No, shared auto just means that the mode chosen was not "drive alone".  In places that have HOV or HOT facilities, it is important to distinguish between "auto" modes - drive alone or shared ride.  The Tahoe ABM includes "joint" tours (2 people from same household going somewhere together) that use the "shared ride" mode and in households where the number of vehicles owned is less than the number of workers, shared ride mode is often selected.   
    
* What is the relation between the 'trip_length_summary' file and the 'DriveDistanceSkim' files?)

> Answer to this question
    
* If we wanted to model a project, like a new event center, how would we go about changing the expected visitation?

 > See answer to "How is Visitor Population determined" above. 
    
* How is census data allocated to the TAZs? (TAZs are smaller than census geometries)?

> This was done originally by TRPA staff.  I am not sure how the TAZs in the model align with the census boundaries.  
    
* Is there a GIS file of the external zones?

> The external zones are part of the TAZ zone layer.  There is a field in the TAZ_District file called "ext_zone" that can be used to select the external zones (join this file to the TAZ.dbd attribute table).  The external zones will also be part of the Highway network file as they are Centroid Nodes - locations where traffic is loaded onto the network.   
    
* All of the residential submodels are calibrated using a Household Travel survey. Where is this survey data?

> I believe I have a copy of the survey results - I suspect TRPA did also at one time.  
    
* The external workers model is based upon the North Tahoe/Truckee Employer Commute survey. Where is this survey data?

> I will look to see if I can find the results from this survey - I believe it was done prior to the original model development project. 
    
* How is the 'model summary' file computed?

> Answer to this question
    
* What is the difference between the 3 versions of 'tour_length' and 'trip_length' files in the reports folder?

> Answer to this question
    
* How can we annualize our peak day VMT?

> Answer to this question 
